version: 2
jobs:
  build:
    docker:
      - image: martinthomson/draft-ietf-tls-tls13-vectors:latest
    working_directory: ~/draft
    steps:
      - checkout

      # Prime caches for faster checkout
      - restore_cache:
          keys:
            - template
      - run:
          name: "Update Template"
          command: "git -C ~/i-d-template remote update --prune"
      - save_cache:
          key: template
          paths:
            - ~/i-d-template

      # Build txt and html versions of drafts
      - restore_cache:
          keys:
            - refcache
            - nss_nspr
      - run:
          name: "Update NSS and NSPR"
          command: |
            [ -d ~/draft/nss ] && hg -q -R ~/draft/nss pull -u https://hg.mozilla.org/projects/nss
            [ -d ~/draft/nspr ] && hg -q -R ~/draft/nspr pull -u https://hg.mozilla.org/projects/nspr
      - save_cache:
          key: nss_nspr
          paths:
            - ~/draft/nss
            - ~/draft/nspr

      - run:
          name: "Build Drafts"
          command: "make 'CLONE_ARGS=--reference ~/i-d-template' 'NSS_OPTIONS=-j 3'"
      - save_cache:
          key: refcache
          paths:
            - ~/.cache/xml2rfc

      # Create and store artifacts
      - run:
          name: "Create Artifacts"
          command: "make artifacts CI_ARTIFACTS=/tmp/artifacts"

      - store_artifacts:
          path: /tmp/artifacts

      # Update gh-pages and gh-issues branches
      - run:
          name: "Update GitHub Pages"
          command: "make gh-pages"

      - run:
          name: "Save Issues"
          command: "make gh-issues || true"

      # For tagged builds, upload to the datatracker.
      - run:
          name: "Upload to Datatracker"
          command: |
            if [ "${CIRCLE_TAG#draft-}" != "${CIRCLE_TAG}" ]; then
              make upload
            fi
